graph TD
    A[Wake up] -->|Get inspired| B(Make game)
    B --> C{What kind of game?}
    C -->|One| D[Fangame] --> Endless_runner --> Jumping_and_sliding
    C -->|Two| E[Original] --> Platformer --> Jumping_and_sliding
    C -->|Three| F[Text-Based]
