puts "Hello!"
puts "My name is..."
puts "My name is Ralsei, and I'm driving a Mercedes Benz."
puts "I like your Mercedes!"
puts "It's pronounced mehr-say-deez, not mehr-cuh-dis"
puts "Deez."
puts "I was pronouncing Mercedes, not telling you to say deez."
puts "Ok boomer"
puts "WHAT?"
puts "...Boomer."
puts "That means an old person. Get away from me."
puts "Okay then."
puts "There. Some nice peace and qu-"
puts "I FOOLED YOU!"
