puts "I am going to summarize Mega Man X and Mega Man Zero."
puts "Be warned, there are spoilers."
puts "It all starts in the year 21XX."
puts "A robot named X is fighting through a highway, and finds a Maverick named Vile."
puts "If I ever say Maverick, it means a robot that hurts people."
puts "So, Vile weakens X, but Zero appears and defeats Vile."
puts "X then defeats some robots."
puts "Sigma hacks into base. X and Zero destroy his bases."
puts "Then, a dude named Axl joins them."
puts "X, Zero, and Axl together stop Sigma 2 times."
puts "Then, X and Axl are scrap metal a year later, or in the year 22XX."
puts "A scientist named Ciel reboots Zero, and now he fights for the few remaining humans."
puts "A bunch of evil robots are planning evil things. Zero stops them."
puts "The end."
