puts "I am going to summarize the old Mega Man games."
puts "One day in the year 200X, some guy named Dr. Light has invented several robots."
puts "Six of them went haywire. Then, his grand creation Mega Man went out and stopped them."
puts "After that, he found out the truth."
puts "Dr. Wily, the rival of Dr. Light, made the robots go haywire."
puts "Mega Man goes and beats Wily."
puts "After that, he returns to Dr. Light's lab."
puts "A year later, Wily made 8 robots."
puts "Mega Man stops them. Wily's fortress opens up. He heads in."
puts "He wins, and fights several robots."
puts "Then, Wily's really angry."
puts "He spreads a computer virus around."
puts "The virus infects several robots."
puts "Mega Man fights those robots."
puts "However, Mega Man gets the computer virus."
puts "However, another robot, named Roll, gave him the cure."
puts "He gets the cure and fights Wily."
puts "Wily is defeated, and Mega Man goes up to space for the grand finale."
